### PR TITLE
add support for comments in tsx syntax

### PR DESCRIPTION
**Pull request by dsifford**
This PR adds support for comments in tsx syntax since it has been ostensibly missing up until now.

The modifications allow for the following types of comments...

```tsx
const foo = () => (
    <div
        // this is a valid comment
        className="foo"
    >
        {/* this is also a valid comment */}
        {
            // this is also a valid comment
        }
        <h1>Hello world</h1>
    </div>
)
```

Please let me know if I missed something and I'll be glad to adjust.

Thanks for the great syntax!

### CODE REVIEW

**Comment by HerringtonDarkholme** [comment]
Thanks! Can you add some tests in tsx.vader?
You can look at example here. https://github.com/HerringtonDarkholme/yats.vim/blob/master/test/tsx.vader

**Comment by dsifford** [comment]
No prob... I'll try to get to it tonight or tomorrow night. 

I realize now that I forgot to also account for the possibility of block comments inside tags, which is also valid.. In other words...

```tsx
const foo = () => (
  <div
    /* this is valid */
    /* this
is also valid */
    className="foobar"
 />
)
```

I'll add that in as well. 👍

**Comment by dsifford** [comment]
Should be all set @HerringtonDarkholme :+1:

**Comment by dsifford** [comment]
Shoot, I'm stupid. I put them in the wrong test file... I'll move the tests over now to the correct file

**Comment by dsifford** [comment]
Now we're all set

**Pull request merged**
