### PR TITLE
tsx comment block indentation

### LINKED ISSUE #167: Comment block not triggered in `.tsx` files
In a `.ts` file I can start typing `/**` and a new line will read ` * `, letting me type in a comment block.

Doing the same in a `.tsx`, a new line just shows up, no indentation.

In a `.ts` file
```
/**
 * You end up here
 * and I can write multiline comments
 * <- CURSOR POSITION
```

In a `.tsx` file
```
/**
<- CURSOR ENDS UP HERE
```

### PR DESCRIPTION
**Pull request by dcchuck**
Resolves #167

### CODE REVIEW

**Comment by HerringtonDarkholme** [comment]
I'm not familiar with the option here. Would you like give me a brief explanation?

**Comment by dcchuck** [comment]
The `-=` and `+=` operators make changes to formatoptions

`formatoptions-=t` - removes `"Auto-wrap text using textwidth"` from the format options

`formatoptions+=croql` - adds
* `c` - Auto-wrap comments using textwidth, inserting the current comment leader automatically.
* `r` - Insert comment leader after hitting `<Enter>` in insert mode
* `o` - Indsert comment leader after hitting `o` or `O` in normal mode
* `q` - Allow formatting of comments with "gq"
* `l` - Long lines not broken when in insert mode

The lines are in `typescript.vim` - [link](https://github.com/HerringtonDarkholme/yats.vim/blob/master/ftplugin/typescript.vim#L14)

If there's a better place to include in both I will happily move it

**Comment by HerringtonDarkholme** [comment]
Thanks!

**Comment by mttrms** [comment]
@danifus you might be interested in [this PR](https://github.com/HerringtonDarkholme/yats.vim/pull/175) that addresses a bug I believe was introduced with this commit.

**Comment by dcchuck** [comment]
@mttrms - `TIL` - thanks for the follow up, I will be sure to pay it forward

**Pull request merged**
