### PR TITLE
[WIP] Revert to official typescriptreact filetype

### PR DESCRIPTION
**Pull request by impulse**
#139 

WIP! Syntax highlighting is not working, some tests fail. Could use some help here.

### CODE REVIEW

**Comment by HerringtonDarkholme** [comment]
What's more should be done here?

**Comment by HerringtonDarkholme** [comment]
I have fixed the problem and test passed!

**Comment by HerringtonDarkholme** [comment]
Thanks!

**Comment by impulse** [comment]
Thanks, couldn't figure it out 😆

**Comment by dsifford** [comment]
Why was this merged? The previous way of including modified filetypes (compounded by using a `.`) was the correct way.

This change completely blew up the theme I maintain.

**Comment by dsifford** [comment]
Disregard my last. Should have read the linked issue. Looks like vim proper is using `typescriptreact` and `javascriptreact` now, which seems strange, but whatever that's fine.

**Pull request merged**
