### PR TITLE
refactor(#117): Give special group name to test keywords

### PR DESCRIPTION
**Pull request by crusoexia**
The group name is 'typescriptTestKeyword'

### CODE REVIEW

**Comment by crusoexia** [comment]
`HiLink` the `typescriptTestKeyword` as `Keyword`, personally think it's more suit than `Constant`.

**Comment by crusoexia** [comment]
Got it, will update.

**Comment by crusoexia** [comment]
Updated.

As I'm not quiet sure what's the original intend to highlight the none `contained` auto-generated groups as `Structure`, I just leave it as is and override it in the `common.vim` to `Keyword`.

**Comment by HerringtonDarkholme** [comment]
I have updated the generating script. I think it should get `contained` statement removed.

**Comment by crusoexia** [comment]
Updated and regenerated.

**Comment by HerringtonDarkholme** [comment]
Thanks!

**Comment by dsifford** [comment]
Why would this not be scoped to type `Function` since these are, indeed, functions. Can we please reconsider this?

**Comment by crusoexia** [comment]
@dsifford Yes they are just functions, but these functions are widely adopt by test runners and almost the standard APIs for testing. Here we want to detect these special functions and give them a group name so that it gives theme the possibility to 'theme' these groups differently.

I don't think the theme should have the responsibility to detect special languages' syntax/special stuffs, it should leverage on the syntax plugins, also that's why we want these syntax plugins.

**Comment by dsifford** [comment]
Right, but the syntax should not be the arbiter of deciding whether or not the "special" functions receive "special" highlight colors. That is the responsibility of the _theme_. 

The syntax can, and sometimes should, apply a special, more specific scope of  function (as done here) but that scope should not make any decisions about whether or not a **function** should be colored like a **keyword**. That is the responsibility of the theme. Period.

If the decision is to move forward with this, I'm going to have to fork this repo and maintain it myself, because I am strongly against this decision.

**Comment by crusoexia** [comment]
@dsifford I think I misunderstood your initial meaning. I'm ok with this, to 'scope' the `typescriptTestGlobal` to `Function`. @HerringtonDarkholme If you are ok with this I will create another pr for the changes.

**Comment by dsifford** [comment]
Yes, that's what I meant. Sorry for maybe coming off rude or hostile before. Hadn't had my breakfast yet. :confounded:

**Comment by crusoexia** [comment]
That's ok, these arguments make the things we rely on moving forward.

**Pull request merged**
